# Generated by Django 3.2.11 on 2022-05-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='COMPANY UNDEF', default='', max_length=1000)),
                ('inn', models.CharField(blank='', default='', max_length=120)),
                ('kpp', models.CharField(blank='', default='', max_length=10000)),
                ('ogrn', models.CharField(blank='', default='', max_length=10000)),
                ('fio', models.CharField(blank='', default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate', models.CharField(max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
            ],
        ),
    ]
