# Generated by Django 3.2.11 on 2022-05-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
